services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - 4200:4200
    environment:
      - APP_ENV=dev
      - APP_PORT=4200
      - APP_PREFIX=api/v1
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
      - RABBIT_MQ_AUTH_QUEUE=auth-queue
    restart: on-failure
    depends_on:
      - auth-service
    networks:
      - api-gateway

  auth-service:
    build:
      context: ./auth-service
    environment:
      - APP_ENV=dev
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
      - RABBIT_MQ_AUTH_QUEUE=auth-queue
    restart: on-failure
    networks:
      - api-gateway

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - api-gateway

  mongo-db:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-db
    ports:
      - 27017:27017

networks:
  api-gateway:
  mongo-db:

volumes:
  mongo-data:
