services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - api-gateway

  mongo-db:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
      - ./seed.js:/docker-entrypoint-initdb.d/seed.js
    networks:
      - mongo-db
    ports:
      - 27017:27017

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - api-gateway

networks:
  api-gateway:
  mongo-db:

volumes:
  mongo-data:
